keys:
  - &admin_josh 2EE325D71601671696EBF687E45953D34C8829ED
  - &signi_age age100uztnkcqanyhq2v37lwq2jtg8563lz25w22u88qhppld526t9zsxy3n3h

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *signi_age
