{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../../profiles/server.nix
  ];

  # ── Secrets (sops-nix) ────────────────────────────────────────
  # Decrypts using the host's SSH ed25519 key (auto-generated by NixOS on Linode)
  sops = {
    defaultSopsFile = ../../secrets/liver.yaml;
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
    secrets = {
      "couchmail/password" = { };
      "couchdb/env" = { };
      "ghost/env" = { };
      "acme/gce_credentials" = { };
      "xmpp/s3secret" = { };
    };
  };

  # ── Boot (Linode GRUB + lish console) ─────────────────────────
  boot.loader.grub = {
    enable = true;
    forceInstall = true;
    device = "nodev";
    extraConfig = ''
      serial --speed=19200 --unit=0 --word=8 --parity=no --stop=1;
      terminal_input serial;
      terminal_output serial
    '';
  };
  boot.loader.timeout = 10;
  boot.kernelParams = [ "console=ttyS0,19200n8" ];

  # ── System ────────────────────────────────────────────────────
  system.stateVersion = "23.05";

  system.autoUpgrade = {
    enable = true;
    dates = "04:00";
    flake = "github:joshperry/mynix";
    allowReboot = true;
  };

  networking.hostName = "liver";
  time.timeZone = "MST7MDT";
  i18n.defaultLocale = "en_US.UTF-8";

  environment.systemPackages = with pkgs; [
    inetutils
    mtr
    sysstat
    dovecot_pigeonhole
  ];

  # ── Users ─────────────────────────────────────────────────────
  users.users.josh = {
    uid = 1000;
    group = "josh";
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICsPaFplk95wdbZnGF9q1LnQUKy36Lh+4dSHyFJwMeUK josh@6bit.com"
    ];
  };
  users.groups.josh = { gid = 1000; };

  users.users.ada = {
    uid = 1100;
    group = "ada";
    isNormalUser = true;
    hashedPassword = "!";
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH4wKwiX1fnwB/U4Mc7JT4ddMExopexk0DUSd7Du12Sp ada@signi"
    ];
  };
  users.groups.ada = { gid = 1100; };

  security.sudo.extraRules = [{
    users = [ "ada" ];
    commands = [
      { command = "/nix/store/*/bin/switch-to-configuration"; options = [ "NOPASSWD" ]; }
      { command = "/run/current-system/sw/bin/nix-env"; options = [ "NOPASSWD" ]; }
    ];
  }];

  # Mail user for virtual mailbox delivery
  users.users.vmail = {
    uid = 5000;
    group = "vmail";
    home = "/var/spool/mail/vhosts";
    isSystemUser = true;
  };
  users.groups.vmail = { gid = 5000; };

  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "no";
  };

  # ── Bind mounts (old Gentoo disk at /mnt/old) ────────────────
  fileSystems."/var/spool/mail/vhosts" = {
    device = "/mnt/old/var/spool/mail/vhosts";
    depends = [ "/mnt/old" ];
    options = [ "bind" ];
  };
  fileSystems."/var/lib/couchdb" = {
    device = "/mnt/old/var/lib/couchdb";
    depends = [ "/mnt/old" ];
    options = [ "bind" ];
  };
  fileSystems."/var/lib/ghost" = {
    device = "/mnt/old/home/josh/dockstacks/curiouslynerdy/ghost/content";
    depends = [ "/mnt/old" ];
    options = [ "bind" ];
  };
  fileSystems."/var/www/6bit.com" = {
    device = "/mnt/old/var/www/6bit.com";
    depends = [ "/mnt/old" ];
    options = [ "bind" "ro" ];
  };
  fileSystems."/var/www/spub" = {
    device = "/mnt/old/var/lib/docker/volumes/sync_sync_storage/_data/folders/public";
    depends = [ "/mnt/old" ];
    options = [ "bind" "ro" ];
  };

  # ── ACME / Let's Encrypt ──────────────────────────────────────
  security.acme = {
    acceptTerms = true;
    defaults.email = "josh@6bit.com";

    certs."6bit.com" = {
      domain = "6bit.com";
      extraDomainNames = [ "*.6bit.com" ];
      dnsProvider = "gcloud";
      credentialFiles = {
        "GCE_SERVICE_ACCOUNT_FILE" = config.sops.secrets."acme/gce_credentials".path;
      };
      reloadServices = [ "postfix.service" "dovecot2.service" "prosody.service" ];
      group = "nginx";
    };

    certs."curiouslynerdy.com" = {
      domain = "curiouslynerdy.com";
      dnsProvider = "gcloud";
      credentialFiles = {
        "GCE_SERVICE_ACCOUNT_FILE" = config.sops.secrets."acme/gce_credentials".path;
      };
      group = "nginx";
    };
  };

  # ── Postfix ───────────────────────────────────────────────────
  services.postfix = {
    enable = true;
    hostname = "mail.6bit.com";
    origin = "$mydomain";
    destination = [ "localhost.$mydomain" "localhost" "$myhostname" ];

    config = {
      # TLS
      smtpd_tls_security_level = "may";
      smtpd_tls_auth_only = "yes";
      smtpd_tls_cert_file = "/var/lib/acme/6bit.com/fullchain.pem";
      smtpd_tls_key_file = "/var/lib/acme/6bit.com/key.pem";
      smtp_tls_security_level = "dane";
      smtp_dns_support_level = "dnssec";

      # SASL via dovecot
      smtpd_sasl_type = "dovecot";
      smtpd_sasl_path = "private/dovecot-auth";
      smtpd_sasl_auth_enable = "yes";

      # Virtual domains via couchmail module (TCP services)
      virtual_transport = "lmtp:unix:private/dovecot-lmtp";
      virtual_uid_maps = "static:5000";
      virtual_gid_maps = "static:5000";

      # Local delivery
      home_mailbox = ".maildir/";
      local_recipient_maps = "";
      recipient_delimiter = "+";
      soft_bounce = "yes";
      mynetworks_style = "host";
      smtpd_banner = "$myhostname ESMTP";

      # DKIM via opendkim milter
      smtpd_milters = "inet:localhost:8891";
      non_smtpd_milters = "inet:localhost:8891";

      # Anti-spam restrictions
      smtpd_helo_required = "yes";
      smtpd_helo_restrictions = "permit_sasl_authenticated, reject_non_fqdn_hostname, reject_invalid_hostname";
      smtpd_sender_restrictions = "reject_non_fqdn_sender, reject_unknown_sender_domain";
      smtpd_relay_restrictions = "permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination";
      smtpd_recipient_restrictions = lib.concatStringsSep ", " [
        "permit_mynetworks"
        "permit_sasl_authenticated"
        "reject_unauth_pipelining"
        "reject_unknown_reverse_client_hostname"
        "check_policy_service unix:postgrey/socket"
        "reject_rbl_client zen.spamhaus.org"
        "reject_rbl_client bl.spamcop.net"
      ];

    };

    masterConfig = {
      # content_filter on smtp inet only — NOT in main.cf — so that
      # re-injected mail via sendmail/pickup doesn't loop back through the filter
      smtp_inet = {
        args = [ "-o" "content_filter=spamfilter" ];
      };
      submission = {
        type = "inet";
        private = false;
        command = "smtpd";
        args = [
          "-o" "syslog_name=postfix/submission"
          "-o" "smtpd_tls_security_level=encrypt"
        ];
      };
      smtps = {
        type = "inet";
        private = false;
        command = "smtpd";
        args = [
          "-o" "syslog_name=postfix/smtps"
          "-o" "smtpd_tls_wrappermode=yes"
        ];
      };
      spamfilter = {
        type = "unix";
        privileged = true;
        chroot = false;
        command = "pipe";
        args = [
          "flags=Rhu"
          "user=spamd"
          "argv=${pkgs.spamassassin}/bin/spamc"
          "-u" "\${user}@\${domain}"
          "-e" "/run/wrappers/bin/sendmail"
          "-oi" "-f" "\${sender}" "\${recipient}"
        ];
        maxproc = 10;
      };
    };

  };

  # ── Dovecot ───────────────────────────────────────────────────
  services.dovecot2 = {
    enable = true;
    enableImap = true;
    enableLmtp = true;
    mailLocation = "maildir:/var/spool/mail/vhosts/%d/%n/.maildir";
    sslServerCert = "/var/lib/acme/6bit.com/fullchain.pem";
    sslServerKey = "/var/lib/acme/6bit.com/key.pem";
    enablePAM = false;

    mailPlugins.perProtocol.lmtp.enable = [ "sieve" ];
    mailPlugins.globally.enable = [ "zlib" ];

    extraConfig = ''
      # Auth + sieve via couchmail module (passdb dict + sieve plugin)
      userdb {
        driver = static
        args = uid=5000 gid=5000 home=/var/spool/mail/vhosts/%d/%n
      }

      plugin {
        zlib_save_level = 6
        zlib_save = gz
      }

      # UID constraints (vmail user)
      first_valid_uid = 5000
      last_valid_uid = 5000

      service lmtp {
        unix_listener /var/lib/postfix/queue/private/dovecot-lmtp {
          user = postfix
          group = postfix
          mode = 0666
        }
      }

      service auth {
        unix_listener /var/lib/postfix/queue/private/dovecot-auth {
          user = postfix
          group = postfix
          mode = 0666
        }
        # Prosody XMPP auth
        unix_listener /run/prosody/dovecot-auth {
          user = prosody
          group = prosody
          mode = 0660
        }
      }
    '';
  };

  # ── OpenDKIM ──────────────────────────────────────────────────
  services.opendkim = {
    enable = true;
    selector = "dkim";
    domains = "csl:6bit.com";
    keyPath = "/var/lib/opendkim/keys";
    socket = "inet:8891@localhost";
  };

  # Copy DKIM key from old disk on first boot (runs as a oneshot before opendkim)
  systemd.services.opendkim-key-init = {
    description = "Initialize OpenDKIM key from old disk";
    before = [ "opendkim.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      mkdir -p /var/lib/opendkim/keys/6bit.com
      if [ ! -f /var/lib/opendkim/keys/6bit.com/dkim.private ] && [ -f /mnt/old/etc/opendkim/dkim.private ]; then
        cp /mnt/old/etc/opendkim/dkim.private /var/lib/opendkim/keys/6bit.com/dkim.private
      fi
      chown -R opendkim:opendkim /var/lib/opendkim
      chmod 600 /var/lib/opendkim/keys/6bit.com/dkim.private
    '';
  };

  # ── Postgrey ──────────────────────────────────────────────────
  services.postgrey = {
    enable = true;
    socket = {
      path = "/var/lib/postfix/queue/postgrey/socket";
      mode = "0666";
    };
  };

  # Ensure postgrey socket dir exists inside the postfix queue
  systemd.tmpfiles.rules = [
    "d /var/lib/postfix/queue/postgrey 0755 postgrey postgrey -"
  ];

  # ── SpamAssassin ──────────────────────────────────────────────
  services.spamassassin.enable = true;

  # ── Couchmail (CouchDB + mail bridge + web UI) ────────────────
  services.couchmail = {
    enable = true;
    domain = "6bit.com";
    couchdbCredentialsFile = config.sops.secrets."couchdb/env".path;
    bridgePasswordFile = config.sops.secrets."couchmail/password".path;
    nginx = {
      enable = true;
      virtualHost = "6bit.com";
    };
  };

  # ── OCI Containers ────────────────────────────────────────────
  virtualisation.oci-containers.backend = "docker";
  virtualisation.docker.enable = true;

  virtualisation.oci-containers.containers = {
    ghost = {
      image = "ghost:5.75-alpine";
      ports = [ "127.0.0.1:2368:2368" ];
      volumes = [ "/var/lib/ghost:/var/lib/ghost/content" ];
      environment = {
        url = "https://curiouslynerdy.com";
        "database__client" = "sqlite3";
        "database__connection__filename" = "content/data/ghost.db";
        "mail__transport" = "SMTP";
        "mail__from" = "ghost@curiouslynerdy.com";
        "mail__options__host" = "mail.6bit.com";
        "mail__options__port" = "587";
      };
      environmentFiles = [ config.sops.secrets."ghost/env".path ];
    };

    sync = {
      image = "resilio/sync";
      ports = [
        "55555:55555"
        "55555:55555/udp"
        "127.0.0.1:8888:8888"
      ];
      volumes = [ "sync_storage:/mnt/sync" ];
    };
  };

  # ── Nginx reverse proxy ───────────────────────────────────────
  services.nginx = {
    enable = true;
    recommendedTlsSettings = true;
    recommendedOptimisation = true;
    recommendedGzipSettings = true;
    recommendedProxySettings = true;

    virtualHosts."6bit.com" = {
      serverAliases = [ "www.6bit.com" ];
      forceSSL = true;
      useACMEHost = "6bit.com";
      root = "/var/www/6bit.com";
      locations."/couch/" = {
        proxyPass = "http://localhost:5984/";
      };
      # Couchmail web UI + API locations provided by services.couchmail.nginx
      locations."/spub/" = {
        alias = "/var/www/spub/";
        extraConfig = "autoindex on;";
      };
    };

    virtualHosts."curiouslynerdy.com" = {
      forceSSL = true;
      useACMEHost = "curiouslynerdy.com";
      locations."/" = {
        proxyPass = "http://localhost:2368";
        extraConfig = "client_max_body_size 20M;";
      };
    };

    virtualHosts."xmpp.6bit.com" = {
      forceSSL = true;
      useACMEHost = "6bit.com";
      locations."/upload/" = {
        proxyPass = "http://127.0.0.1:5050";
        extraConfig = "client_max_body_size 500M;";
      };
      locations."/" = {
        proxyPass = "http://localhost:5280";
      };
    };

    virtualHosts."sync.6bit.com" = {
      forceSSL = true;
      useACMEHost = "6bit.com";
      locations."/" = {
        proxyPass = "http://localhost:8888";
      };
    };
  };

  # Grant nginx access to ACME certs
  users.users.nginx.extraGroups = [ "acme" ];
  users.users.prosody.extraGroups = [ "nginx" ];

  # Dovecot creates its auth socket inside /run/prosody/ (prosody's RuntimeDirectory).
  # If prosody restarts, systemd wipes that directory, so dovecot must also restart
  # (after prosody) to recreate the socket.
  systemd.services.dovecot.partOf = [ "prosody.service" ];
  systemd.services.dovecot.after = [ "prosody.service" ];

  # ── Prosody (XMPP) ───────────────────────────────────────────
  services.prosody = {
    enable = true;
    xmppComplianceSuite = false;
    admins = [ "josh@6bit.com" ];

    ssl = {
      cert = "/var/lib/acme/6bit.com/fullchain.pem";
      key = "/var/lib/acme/6bit.com/key.pem";
    };

    modules = {
      # Generally required
      roster = true;
      saslauth = true;
      tls = true;
      dialback = true;
      disco = true;
      # Recommended
      private = true;
      vcard_legacy = true;
      # Nice to have
      version = true;
      uptime = true;
      time = true;
      ping = true;
      pep = true;
      register = true;
      # Admin
      admin_adhoc = true;
      # Mobile essentials
      carbons = true;      # XEP-0280: sync messages across devices
      mam = true;          # XEP-0313: message archive (history sync)
      smacks = true;       # XEP-0198: stream management (reconnect)
      csi = true;          # XEP-0352: client state indication (battery)
      # Push
      cloud_notify = true; # XEP-0357: push notifications
      # Quality of life
      blocklist = true;    # XEP-0191: block contacts
      bookmarks = true;    # XEP-0402: MUC bookmarks sync
    };

    # mod_auth_dovecot is a community module baked into the package
    package = pkgs.prosody.override {
      withCommunityModules = [
        "auth_dovecot"
        "http_upload_external"  # XEP-0363: delegates uploads to prosody-filer-s3
        "unified_push"          # Self-hosted UnifiedPush provider
      ];
    };

    httpInterfaces = [ "127.0.0.1" ];
    httpPorts = [ 5280 ];

    allowRegistration = false;
    c2sRequireEncryption = true;
    s2sSecureAuth = false;

    # Authentication via Dovecot (overrides the enum-restricted option)
    extraConfig = ''
      authentication = "dovecot"
      dovecot_auth_socket = "/run/prosody/dovecot-auth"
      auth_append_host = true
      network_backend = "event"

      -- Stream management (mod_smacks)
      smacks_hibernation_time = 300
      smacks_max_hibernated_sessions = 10
      smacks_max_old_sessions = 10

      -- Message archive (mod_mam)
      default_archive_policy = true
      max_archive_query_results = 50

      -- Push notifications (mod_cloud_notify)
      push_notification_important_body = "New message"
      push_max_errors = 16
      push_max_devices = 5

      -- File upload (mod_http_upload_external → prosody-filer-s3 → Linode S3)
      http_upload_external_base_url = "https://xmpp.6bit.com/upload/"
      http_upload_external_file_size_limit = 524288000 -- 500MB

      -- Read HMAC secret shared with prosody-filer-s3
      local hmac_file = io.open("/var/lib/prosody-filer-s3/hmac-secret", "r")
      if hmac_file then
        http_upload_external_secret = hmac_file:read("*l")
        hmac_file:close()
      end

      -- HTTP settings for UnifiedPush endpoint
      http_external_url = "https://xmpp.6bit.com/"
    '';

    virtualHosts."6bit.com" = {
      enabled = true;
      domain = "6bit.com";
      ssl = {
        cert = "/var/lib/acme/6bit.com/fullchain.pem";
        key = "/var/lib/acme/6bit.com/key.pem";
      };
    };

    muc = [
      { domain = "conference.6bit.com"; }
    ];

  };


  # ── Prosody Filer S3 (XEP-0363 upload handler) ───────────────
  # Receives HMAC-signed uploads from XMPP clients, streams to Linode S3.
  # Downloads redirect to presigned S3 URLs — liver never serves file data.

  # Generate HMAC shared secret on first boot (shared between prosody + filer)
  systemd.services.prosody-filer-s3-init = {
    description = "Generate prosody-filer-s3 HMAC secret";
    before = [ "prosody.service" "prosody-filer-s3.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      mkdir -p /var/lib/prosody-filer-s3
      if [ ! -f /var/lib/prosody-filer-s3/hmac-secret ]; then
        ${pkgs.openssl}/bin/openssl rand -base64 32 > /var/lib/prosody-filer-s3/hmac-secret
      fi
      chmod 640 /var/lib/prosody-filer-s3/hmac-secret
      chown root:prosody /var/lib/prosody-filer-s3/hmac-secret

      # Build config from template + secrets
      HMAC_SECRET=$(cat /var/lib/prosody-filer-s3/hmac-secret)
      S3_SECRET=$(cat ${config.sops.secrets."xmpp/s3secret".path})
      cat > /var/lib/prosody-filer-s3/config.toml << EOF
      ListenPort = "127.0.0.1:5050"
      Secret = "$HMAC_SECRET"
      UploadSubDir = "upload/"
      S3Endpoint = "us-lax-1.linodeobjects.com"
      S3TLS = true
      S3AccessKey = "F4678DQ3UU1BT8V0SWNV"
      S3Secret = "$S3_SECRET"
      S3Bucket = "xmpp-media"
      S3Region = "us-lax-1"
      ProxyMode = false
      EOF
      chmod 640 /var/lib/prosody-filer-s3/config.toml
    '';
  };

  systemd.services.prosody-filer-s3 = {
    description = "Prosody HTTP upload handler (S3 backend)";
    after = [ "network.target" "prosody-filer-s3-init.service" ];
    requires = [ "prosody-filer-s3-init.service" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      ExecStart = "${pkgs.mynix.prosody-filer-s3}/bin/prosody-filer-s3 -config /var/lib/prosody-filer-s3/config.toml";
      Restart = "on-failure";
      RestartSec = 5;
      NoNewPrivileges = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateTmp = true;
      ReadOnlyPaths = [ "/var/lib/prosody-filer-s3" ];
    };
  };

  # ── IPv6 ─────────────────────────────────────────────────────
  # Docker enables IPv6 forwarding, which disables accept_ra.
  # Set accept_ra=2 to accept RAs even with forwarding enabled.
  # Disable privacy extensions — Linode only routes the SLAAC address.
  boot.kernel.sysctl = {
    "net.ipv6.conf.eth0.accept_ra" = 2;
    "net.ipv6.conf.eth0.use_tempaddr" = lib.mkForce 0;
  };

  # ── Firewall ──────────────────────────────────────────────────
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [
      22    # SSH
      25    # SMTP
      80    # HTTP
      143   # IMAP
      443   # HTTPS
      465   # SMTPS
      587   # Submission
      993   # IMAPS
      5222  # XMPP client
      5269  # XMPP server
      55555 # Resilio Sync
    ];
    allowedUDPPorts = [
      55555 # Resilio Sync
    ];
  };

  # ── fail2ban ──────────────────────────────────────────────────
  services.fail2ban = {
    enable = true;
    jails = {
      postfix.settings = { enabled = true; };
      dovecot.settings = { enabled = true; };
      sshd.settings = { enabled = true; };
    };
  };

  # ── Unfree packages ──────────────────────────────────────────
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "resilio-sync"
  ];
}
